### ISSUE TITLE
'weather/{lat,long}' broke sometimes

### ISSUE THREAD

**Issue by semir4in** [DB-db-dron/weatherDB#10]
Hello. thank you for making non-api-key db in advance. I'm so glad that I can embed weather tab in my app so easily.

**Describe the bug**
I got `lat,long` from chrome locator and tried get response weatherdbi:
```javascript
// in javascript
const longitude = position.coords.longitude; // chrome function
const latitude = position.coords.latitude; // chrome function
const url = `https://weatherdbi.herokuapp.com/data/weather/${latitude},${longitude}`;
```
but I got failed response with the location nearby my home. After that day, I checked the same code in other place and got the right response. So, for more infomation, I checked these regions in google map that they are indicating certain place in South Korea. And here's the things..

**To Reproduce**
Four examples with very small changes ~ 0.1 changes in longitude:

- https://weatherdbi.herokuapp.com/data/weather/37.407812,127.171824
Response -> region: Jungwon-gu, Seongnam-si, Gyeonggi-do, South Korea

- https://weatherdbi.herokuapp.com/data/weather/37.407812,127.071824
Response -> message: invalid query

- https://weatherdbi.herokuapp.com/data/weather/37.407812,126.971824
Response -> message: invalid query

- https://weatherdbi.herokuapp.com/data/weather/37.407812,126.871824
Response -> region: Hagon-dong, Gwangmyeong-si, Gyeonggi-do, South Korea

It doesn't seem to work in certain sections. It's a difficult problem to guess because I can't look inside the code. Can you figure it out? If you can catch the reason, please fix it for useful weather database 😎

**Comment by SGtOriginal** [comment]
See [this comment](https://github.com/DB-db-dron/weatherDB/issues/8#issuecomment-1157204141) by the owner.

**Comment by DB-db-dron** [comment]
[127.171824](https://weatherdbi.herokuapp.com/data/weather/37.407812,127.171824) => 127 degrees, 10 minutes, 18.5664 seconds

[127.071824](https://weatherdbi.herokuapp.com/data/weather/37.407812,127.071824) => 127 degrees, 4 minutes, 18.5664 seconds

In the present implementation, the coordinates work at locality level precision (that is - local area name inside a city). But the processing of your invalid coordinates `37.407812,127.071824` gives back locality name as `13452` which I think is the postal code. A similar observation was recorded for the other invalid query. 

This is happening due to the third-party service that we use for our API, hence cannot be fixed somehow. The locality name is important for further processing, but its being a number causes this issue.

**Comment by semir4in** [comment]
It's a little sad that the unwanted transformation is happening at 3rd party. If I can change the coordinates to a city name, this problem can be solved easily.
Thank you for your kind reply. Have a good weekend!
